name: "Setup"
description: "Setup tooling"
runs:
  using: "composite"
  steps:
    - name: Cache turbo
      uses: actions/cache@v3
      with:
        path: |
          .turbo
          **/.turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Cache scarb
      uses: actions/cache@v3
      with:
        path: |
          target/
          **/target/
        key: ${{ runner.os }}-scarb-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-scarb-

    - uses: pnpm/action-setup@v3
      with:
        version: 10

    - name: Install dojo
      run: |
        curl -L -o dojo-linux-x86_64.tar.gz https://github.com/dojoengine/dojo/releases/download/${{ env.DOJO_VERSION }}/dojo_${{ env.DOJO_VERSION }}_linux_amd64.tar.gz
        tar -xzf dojo-linux-x86_64.tar.gz
        sudo mv sozo /usr/local/bin/
      shell: bash

    - name: Install packages
      run: pnpm install --frozen-lockfile
      shell: bash
