[world]
name = "Marketplace"
description = "Cartridge marketplace, powered by Dojo toolchain"
website = "https://github.com/cartridge-gg/marketplace"
seed = "marketplace"

[world.socials]
x = "https://x.com/cartridge_gg"
github = "https://github.com/cartridge-gg/marketplace"

[namespace]
default = "MARKETPLACE"

[init_call_args]
"MARKETPLACE-Marketplace" = [
  "0x1F4",                                                              # 5% fee
  "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b", # Fee receiver
  "0x041aad5a7493b75f240f418cb5f052d1a68981af21e813ed0a35e96d3e83123b", # Owner
]

[env]
rpc_url = "http://localhost:5050/"
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"

[writers]
"MARKETPLACE" = ["MARKETPLACE-Marketplace"]
