packages:
  - client
  - packages/*
  - contracts
catalog:
  '@cartridge/ui': github:cartridge-gg/ui#3fa3547
  '@cartridge/controller': 0.7.13
  '@cartridge/connector': 0.7.13
  '@starknet-react/core': 3.7.4
  '@starknet-react/chains': 3.1.3
  '@dojoengine/core': 1.5.5
  '@dojoengine/sdk': 1.5.5
  '@dojoengine/torii-client': 1.5.5
  '@dojoengine/torii-wasm': 1.5.5
  class-variance-authority: ^0.7.1
  starknet: 6.23.1
  tsup: 8.4.0
  typescript: '5.8'
overrides:
  '@dojoengine/sdk': link:../../dojo.js/packages/sdk
  react: ^19.0.0
  react-dom: ^19.0.0
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
