[workspace]
members = ["packages/executor"]
description = "Dojo marketplace library"
homepage = "https://github.com/cartridge-gg/marketplace"
cairo-version = "2.9.4"

[workspace.package]
version = "0.0.0"
edition = "2024_07"

[workspace.dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.4.0" }
starknet = "2.9.4"
cairo_test = "2.9.4"

[workspace.tool.fmt]
sort-module-level-items = true
