rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x63f36b6d15411e82ee9e4e9b17c3889f45c0c4714e7d53a3317dca197dceac5"

[indexing]
events_chunk_size = 1024
blocks_chunk_size = 1024
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 1445691
contracts = []

[sql]
historical = []
