rpc = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x0721a3b839f2f1011da15799710e74eae77d9ff0292cfd13b3e6f1357bccccf2"

[indexing]
events_chunk_size = 1024
blocks_chunk_size = 1024
pending = true
polling_interval = 500
max_concurrent_tasks = 100
world_block = 1460131
contracts = []

[sql]
historical = []
