[package]
name = "executor"
version.workspace = true
edition.workspace = true

[dependencies]
dojo.workspace = true

[dev-dependencies]
dojo_cairo_test.workspace = true
cairo_test.workspace = true

[lib]

[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]
