[package]
cairo-version = "2.10.1"
edition = "2024_07"
name = "marketplace"
version = "0.0.4"

[cairo]
sierra-replace-ids = true

[scripts]
dev = "sozo clean && sozo build --typescript && sozo migrate plan && sozo migrate apply"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
orderbook = { path = ".." }
starknet = "2.10.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.5.1" }
cairo_test = "2.10.1"

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "orderbook::models::index::m_Access",
    "orderbook::models::index::m_Book",
    "orderbook::models::index::m_Order",
    "orderbook::models::index::m_MetadataAttribute",
    "orderbook::events::index::e_Listing",
    "orderbook::events::index::e_Offer",
    "orderbook::events::index::e_Sale",
]

[profile.mainnet]
